FROM python:3.9-slim
LABEL version="{{apiserver-version}}"
LABEL service_name="apiserver"
WORKDIR /usr/src/app
COPY ../../setup.py ./
COPY ../../pyproject.toml ./
ADD ../../spatialprofilingtoolbox/ ./spatialprofilingtoolbox
RUN pip3 install .[apiserver]
COPY ./app ./
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--log-level", "debug", "--workers", "9"]
