COPY ./app ./
ENV API_SERVER_PORT=8080
HEALTHCHECK CMD curl --fail http://localhost:${API_SERVER_PORT}/ || exit 1
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${API_SERVER_PORT}", "--log-level", "debug", "--workers", "9"]
