
build-dockerfile:
	@cat ${BUILD_SCRIPTS_LOCATION}/Dockerfile.base ./Dockerfile.append > Dockerfile

unit-tests:
	@echo 'Unit tests.'

module-tests:
	@echo 'Module tests.'

clean:
	@rm -f Dockerfile
	@rm -f ${WHEEL_FILENAME}
