[build-system]
requires = [
    "setuptools>=63",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "spatialprofilingtoolbox"
version = "0.12.2"
authors = [
    { name = "James Mathews", email = "mathewj2@mskcc.org" }
]
description = "Toolbox for spatial analysis of single cell data."
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Science/Research"
]
requires-python = ">=3.9"
dependencies = [
    "psycopg2==2.9.3",
    "adiscstudies==0.10.10"
]

[project.urls]
documentation = "https://github.com/nadeemlab/SPT"
repository = "https://github.com/nadeemlab/SPT"

[project.optional-dependencies]
apiserver = [
    "fastapi>=0.68.0,<0.69.0",
    "uvicorn>=0.15.0,<0.16.0"
]
db = [
    "pandas>=1.1.5",
    "pyshp==2.2.0"
]
countsserver = []
cggnn = [
    "cg-gnn"
]
workflow = [
    "numpy==1.22.3",
    "scipy==1.8.0",
    "scikit-learn==1.1.2",
    "pyshp==2.2.0",
    "pandas>=1.1.5",
    "Jinja2==3.0.1",
    "tabulate==0.8.10"
]
building = [
    "Jinja2==3.0.1"
]
all = [
    "fastapi>=0.68.0,<0.69.0",
    "uvicorn>=0.15.0,<0.16.0",
    "Jinja2==3.0.1",
    "pandas>=1.1.5",
    "numpy==1.22.3",
    "scipy==1.8.0",
    "scikit-learn==1.1.2",
    "pyshp==2.2.0",
    "tabulate==0.8.10"
]
dev = [
    "autopep8",
    "mypy",
    "pylint",
    "pytest"
]

[project.scripts]
spt = "spatialprofilingtoolbox.entry_point.cli:main_program"
spt-enable-completion = "spatialprofilingtoolbox.entry_point.spt_enable_completion:main_program"

[tool.setuptools]
packages = [
    "spatialprofilingtoolbox",
    "spatialprofilingtoolbox.standalone_utilities",
    "spatialprofilingtoolbox.entry_point",
    "spatialprofilingtoolbox.apiserver",
    "spatialprofilingtoolbox.apiserver.app",
    "spatialprofilingtoolbox.apiserver.scripts",
    "spatialprofilingtoolbox.cggnn",
    "spatialprofilingtoolbox.cggnn.scripts",
    "spatialprofilingtoolbox.countsserver",
    "spatialprofilingtoolbox.countsserver.scripts",
    "spatialprofilingtoolbox.db",
    "spatialprofilingtoolbox.db.scripts",
    "spatialprofilingtoolbox.db.data_model",
    "spatialprofilingtoolbox.workflow",
    "spatialprofilingtoolbox.workflow.scripts",
    "spatialprofilingtoolbox.workflow.dataset_designs",
    "spatialprofilingtoolbox.workflow.dataset_designs.multiplexed_imaging",
    "spatialprofilingtoolbox.workflow.defaults",
    "spatialprofilingtoolbox.workflow.phenotype_proximity",
    "spatialprofilingtoolbox.workflow.front_proximity",
    "spatialprofilingtoolbox.workflow.density",
    "spatialprofilingtoolbox.workflow.nearest_distance",
    "spatialprofilingtoolbox.workflow.halo_import",
    "spatialprofilingtoolbox.workflow.common",
    "spatialprofilingtoolbox.workflow.common.logging",
    "spatialprofilingtoolbox.workflow.source_file_adi_parsing",
    "spatialprofilingtoolbox.workflow.templates"
]

[tool.setuptools.package-data]
"spatialprofilingtoolbox.entry_point" = ["spt-completion.sh.jinja"]
"spatialprofilingtoolbox.workflow.scripts" = [
    "aggregate_core_results.py",
    "core_job.py",
    "extract_compartments.py",
    "generate_run_information.py",
    "initialize.py",
    "merge_performance_reports.py",
    "merge_sqlite_dbs.py",
    "report_run_configuration.py",
    "configure.py",
    "report_on_logs.py"
]
"spatialprofilingtoolbox.workflow.workflows" = [
    "main.nf.jinja"
]
"spatialprofilingtoolbox.workflow.templates" = [
    "nextflow.config.jinja",
    "log_table.tex.jinja",
    "log_table.html.jinja",
    ".spt_db.config.template",
    "main.nf.jinja"
]
"spatialprofilingtoolbox.countsserver.scripts" = [
    "read_expression_dump_file.py",
    "cache_expressions_data_array.py",
    "start.py"
]
"spatialprofilingtoolbox.db.scripts" = [
    "create_schema.py",
    "modify_constraints.py",
    "guess_channels_from_object_files.py",
    "status.py",
    "retrieve_feature_matrices.py"
]
"spatialprofilingtoolbox.db.data_model" = [
    "create_roles.sql",
    "create_views.sql",
    "drop_views.sql",
    "fields.tsv",
    "grant_on_tables.sql",
    "performance_tweaks.sql",
    "refresh_views.sql"
]
"spatialprofilingtoolbox.cggnn.scripts" = [
    "run.py",
]
