[build-system]
requires = [
    "setuptools>=63",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "spatialprofilingtoolbox"
version = "0.10.12"
authors = [
    { name = "James Mathews", email = "mathewj2@mskcc.org" }
]
description = "Toolbox for spatial analysis of single cell data."
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Science/Research",
]
requires-python = ">=3.9"
dependencies = [
    "psycopg2-binary==2.9.3",
    "adisinglecell==0.10.2",
]
urls = { "Documentation" = "https://github.com/nadeemlab/SPT", "Source code" = "https://github.com/nadeemlab/SPT" }

[project.optional-dependencies]
apiserver = ["fastapi>=0.68.0,<0.69.0", "uvicorn>=0.15.0,<0.16.0"]
control = ["Jinja2==3.0.1", "pandas>=1.1.5"]
dashboard = ["Jinja2==3.0.1"]
db = ["pandas>=1.1.5"]
workflow = ["numpy==1.22.3", "scipy==1.8.0", "scikit-learn==0.24.1", "pyshp==2.2.0", "pandas>=1.1.5"]
all = ["fastapi>=0.68.0,<0.69.0", "uvicorn>=0.15.0,<0.16.0", "Jinja2==3.0.1", "pandas>=1.1.5", "numpy==1.22.3", "scipy==1.8.0", "scikit-learn==0.24.1", "pyshp==2.2.0"]

[project.scripts]
spt = "spatialprofilingtoolbox.entry_point.spt:main_program"
spt-enable-completion = "spatialprofilingtoolbox.entry_point.spt_enable_completion:main_program"

[tool.setuptools]
packages = [
    "spatialprofilingtoolbox",
    "spatialprofilingtoolbox.standalone_utilities",
    "spatialprofilingtoolbox.entry_point",
    "spatialprofilingtoolbox.apiserver",
    "spatialprofilingtoolbox.apiserver.scripts",
    "spatialprofilingtoolbox.control",
    "spatialprofilingtoolbox.control.scripts",
    "spatialprofilingtoolbox.countsserver",
    "spatialprofilingtoolbox.countsserver.scripts",
    "spatialprofilingtoolbox.dashboard",
    "spatialprofilingtoolbox.dashboard.scripts",
    "spatialprofilingtoolbox.db",
    "spatialprofilingtoolbox.db.scripts",
    "spatialprofilingtoolbox.db.data_model",
    "spatialprofilingtoolbox.workflow",
    "spatialprofilingtoolbox.workflow.scripts",
    "spatialprofilingtoolbox.workflow.dataset_designs",
    "spatialprofilingtoolbox.workflow.dataset_designs.multiplexed_imaging",
    "spatialprofilingtoolbox.workflow.workflows",
    "spatialprofilingtoolbox.workflow.workflows.defaults",
    "spatialprofilingtoolbox.workflow.workflows.phenotype_proximity",
    "spatialprofilingtoolbox.workflow.workflows.front_proximity",
    "spatialprofilingtoolbox.workflow.workflows.density",
    "spatialprofilingtoolbox.workflow.workflows.nearest_distance",
    "spatialprofilingtoolbox.workflow.workflows.halo_import",
    "spatialprofilingtoolbox.workflow.environment",
    "spatialprofilingtoolbox.workflow.environment.logging",
    "spatialprofilingtoolbox.workflow.environment.source_file_parsers",
    "spatialprofilingtoolbox.workflow.templates",
]

[tool.setuptools.package-data]
"spatialprofilingtoolbox.entry_point" = ["spt-completion.sh"]
"spatialprofilingtoolbox.workflow.scripts" = [
    "aggregate-core-results.py",
    "core-job.py",
    "extract-compartments.py",
    "generate-run-information.py",
    "initialize.py",
    "merge-performance-reports.py",
    "merge-sqlite-dbs.py",
    "report-run-configuration.py",
]
"spatialprofilingtoolbox.workflow.workflows" = [
    "main.nf.jinja",
]
"spatialprofilingtoolbox.workflow.templates" = [
    "nextflow.config.jinja",
    "log_table.tex.jinja",
    "log_table.html.jinja",
    ".spt_db.config.template",
]
"spatialprofilingtoolbox.control.scripts" = [
    "configure.py",
    "guess-channels.py",
    "report-on-logs.py",
]
"spatialprofilingtoolbox.countsserver.scripts" = [
    "read-expression-dump-file.py",
    "cache-expressions-data-array.py",
    "start.py",
]
"spatialprofilingtoolbox.db.scripts" = [
    "create-schema.py",
    "modify-constraints.py",
]
"spatialprofilingtoolbox.db.data_model" = [
    "create_roles.sql",
    "create_views.sql",
    "drop_views.sql",
    "fields.tsv",
    "grant_on_tables.sql",
    "performance_tweaks.sql",
    "refresh_views.sql",
]
