
GRANT SELECT ON ALL TABLES IN SCHEMA public TO apireader;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO apireader;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO nadeemlab;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO nadeemlab;
