#!/usr/bin/env python3
"""
This script represents a single job of the front proximity analysis workflow. It
is not run directly by the user.
"""
import argparse

import spatialprofilingtoolbox as spt

if __name__=='__main__':
    parser = argparse.ArgumentParser(
        description = ''.join([
            'This program does cell phenotype-to-region-front proximity calculations in ',
            'multiplexed IF images.',
            'It is formulated as a script so that it can be run as part of large HPC batches. '
            'It generally needs to be run as part of spt-pipeline, to ensure initialization.',
        ])
    )
    parser.add_argument('--input-file-identifier',
        dest='input_file_identifier',
        type=str,
        required=True,
        help='The input file to process.',
    )
    args = parser.parse_args()
    kwargs = {}
    kwargs['input_file_identifier'] = args.input_file_identifier
    parameters = spt.get_config_parameters()
    parameters = {**kwargs, **parameters}
    a = spt.get_analyzer(**parameters)
    a.calculate()
