#!/usr/bin/env python3
import argparse

import spatialprofilingtoolbox as spt

if __name__=='__main__':
    parser = argparse.ArgumentParser(
        description = 'This program does calculations with multiplexed IF images.'
    )
    parser.add_argument('--input-file-identifier',
        dest='input_file_identifier',
        type=str,
        required=True,
        help='Input file identifier, as it appears in the file manifest.',
    )
    parser.add_argument('--fov',
        dest='input_fov',
        type=int,
        required=True,
        help='Ordinality of field of view to consider (i.e. one-based integer index).',
    )
    args = parser.parse_args()
    parameters = {}
    parameters['input_file_identifier'] = args.input_file_identifier
    parameters['fov_index'] = args.input_fov
    parameters = {**parameters, **spt.get_config_parameters()}
    a = spt.get_analyzer(**parameters)
    a.calculate()
