#!/usr/bin/env python3
import argparse
import subprocess
from subprocess import PIPE
from shutil import which
import os
from os.path import join

import spatialprofilingtoolbox as spt

if __name__=='__main__':
    parser = argparse.ArgumentParser(
        description = ''.join([
            'The entry point into SPT (Spatial Profiling Toolbox) ',
            'commands.',
        ])
    )
    aggregate_results = 'aggregate-results'
    commands = [aggregate_results]
    parser.add_argument(
        'command_token',
        nargs='?',
        choices = commands,
    )
    args = parser.parse_args()
    parameters = {}

    command = args.command_token

    if not command in commands:
        exit()

    if command == aggregate_results:
        integrator = spt.get_integrator(**parameters)
        integrator.calculate()
