#!/usr/bin/env python3
import argparse

import spatialprofilingtoolbox as spt
from spatialprofilingtoolbox import FrontProximityViz

if __name__=='__main__':
    parser = argparse.ArgumentParser(
        description=''.join([
            'Visualize density of cells with respect to proximity',
            'to regional/compartment front or boundary.'
        ])
    )
    parser.add_argument(
        'filename',
        type=str,
        help='sqlite database file containing the cell distance data.',
    )
    parser.add_argument(
        '--drop-compartment',
        dest='drop_compartments',
        default=[],
        action='append',
    )
    args = parser.parse_args()
    print(args.drop_compartments)
    gui = FrontProximityViz(
        distances_db_uri=args.filename,
        drop_compartments=args.drop_compartments,
    )
    gui.start_showing()
