#!/usr/bin/env python3
"""
This script represents a single job of the density analysis workflow. It
is not run directly by the user.
"""

import spatialprofilingtoolbox as spt

if __name__=='__main__':
    parameters = spt.get_config_parameters()
    a = spt.get_analyzer(**parameters)
    a.calculate()
