#!/usr/bin/env python3
import argparse

import spatialprofilingtoolbox as spt
from spatialprofilingtoolbox.dataset_designs.multiplexed_imaging.halo_cell_metadata_provider import HALOCellMetadata
from spatialprofilingtoolbox.dataset_designs.multiplexed_imaging.halo_cell_metadata_design import HALOCellMetadataDesign

def do_aggregation():
    parser = argparse.ArgumentParser(
        description = ''.join([
            'This program does cell phenotype-to-region-front proximity calculations in ',
            'multiplexed IF images.',
            'It is formulated as a script so that it can be run as part of large HPC batches. '
            'It generally needs to be run as part of spt-pipeline, to ensure initialization.',
        ])
    )
    parser.add_argument('--max-per-sample',
        dest='max_per_sample',
        type=int,
        required=False,
        default=100,
        help='The maximum number of cells to draw from each sample/image.',
    )
    args = parser.parse_args()

    parameters = spt.get_config_parameters_from_file()
    dataset_design = HALOCellMetadataDesign(
        elementary_phenotypes_file=parameters['elementary_phenotypes_file'],
    )
    cell_data = HALOCellMetadata(
        input_files_path = parameters['input_path'],
        dataset_design = dataset_design,
        file_manifest_file = parameters['file_manifest_file'],
    )
    cell_data.initialize()
    cell_data.write_subsampled(
    	max_per_sample = args.max_per_sample,
    	outcomes_file = parameters['outcomes_file'],
    )

if __name__=='__main__':
    do_aggregation()
