#!/usr/bin/env python3
import sys

import spatialprofilingtoolbox as spt

if __name__=='__main__':
    cli_arguments = sys.argv
    N = len(cli_arguments)
    if N == 2:
        argument = cli_arguments[1]
        if argument == 'config-filename':
            print(spt.config_filename)
        if argument == 'computational-workflows':
            print('\n'.join(list(spt.workflows.keys())))
        if argument == 'version':
            print(spt.__version__)
