#!/usr/bin/env python3
import argparse
import csv

def extract_compartments_single_file(filename):
    with open(filename, 'r') as file:
        reader = csv.reader(file)
        header_row = next(reader)
        key = {header_row[i] : i for i in range(len(header_row))}
        entry = lambda row, name: row[key[name]]
        if not 'Classifier Label' in header_row:
            logger.error('"Classifier Label" is missing from file "%s".', filename)
        compartments = [
            entry(row, 'Classifier Label')
            for row in reader
        ]
        return sorted(list(set(compartments)))

if __name__=='__main__':
    parser = argparse.ArgumentParser(
        description = 'Scan HALO cell manifest files for compartment names.',
    )
    parser.add_argument(
        'cell_manifest',
        dest='cell_manifests',
        nargs='+',
        type=str,
        required=True,
    )
    parser.add_argument(
    	'--compartments-list',
        dest='compartments_list_file',
        type=str,
        required=True,
        help=''.join([
            'Filename for output list of compartment names.',
        ])
    )
    args = parser.parse_args()

    compartments = set([])
    for cell_manifest in args.cell_manifest:
    	compartments = compartments.union(set(
    		extract_compartments_single_file(cell_manifest)
    	))
    compartments = sorted(list(compartments))
    with open(args.compartments_list_file, 'wt') as file:
    	file.write('\n'.join(compartments))
