#!/bin/bash

# "Install" this git hook by copying it to .git/hooks/
# It increments the version number on every commit.

location="spatialprofilingtoolbox/version.txt"
version=$(cat "$location")

if [[ "$OSTYPE" == "darwin"* ]]; then
    prefix=$(echo "$version" | grep -o '^[0-9]\+\.[0-9]\+\.')
    microversion=$(echo "$version" | grep -o '[0-9]\+$')
else
    prefix=$(echo "$version" | grep -oP '^([\d]+\.[\d]+\.)')
    microversion=$(echo "$version" | grep -oP '([\d]+)$')
fi

microversion=$(( microversion + 1 ))
echo "$prefix$microversion" > $location
