import sys

from smprofiler.db.shapefile_polygon import extract_points

if __name__ == '__main__':
    SHAPEFILE_CONTENTS = 'AAAnCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdugDAAAFAAAAAAAAAACatEAAAAAAAAAYwAAAAAAAurRAAAAAAAAAMkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAABABQAAAAAAAAAAmrRAAAAAAAAAGMAAAAAAALq0QAAAAAAAADJAAQAAAAUAAAAAAAAAAAAAAACatEAAAAAAAAAYwAAAAAAAmrRAAAAAAAAAMkAAAAAAALq0QAAAAAAAADJAAAAAAAC6tEAAAAAAAAAYwAAAAAAAmrRAAAAAAAAAGMA='
    points = extract_points(SHAPEFILE_CONTENTS)
    expected = [(5274.0, -6.0), (5274.0, 18.0), (5306.0, 18.0),
                (5306.0, -6.0), (5274.0, -6.0)]
    if expected != points:
        sys.exit(1)
