FROM python:3.9-slim
ARG version
ARG service_name
ARG WHEEL_FILENAME
LABEL version=$version
LABEL service_name=$service_name
ENV service_name $service_name
RUN apt-get update
RUN apt-get -y install gcc
RUN apt-get install -y libpq-dev
WORKDIR /usr/src/app
COPY requirements.txt .
RUN python -m pip install -r requirements.txt
COPY specific_requirements.txt .
RUN python -m pip install -r specific_requirements.txt
COPY $WHEEL_FILENAME ./
RUN pip3 install "$WHEEL_FILENAME"
