FROM ubuntu:20.04

LABEL version="{{version}}"

WORKDIR /usr/src/app

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y install python3-dev
RUN apt-get update && apt-get -y install python3-pip

{{install requirements.txt}}

COPY LICENSE.md ./
COPY setup.py ./
COPY pyproject.toml ./
ADD spatialprofilingtoolbox/ ./spatialprofilingtoolbox
RUN pip install .

ENV DEBUG=1
