
DROP MATERIALIZED VIEW IF EXISTS phenotyping_breakdown_report;
DROP MATERIALIZED VIEW IF EXISTS single_channel_diagnosis_breakdown_report;
DROP MATERIALIZED VIEW IF EXISTS single_channel_all_diagnosis_breakdown_report;
DROP MATERIALIZED VIEW IF EXISTS composite_diagnosis_breakdown_report;
DROP MATERIALIZED VIEW IF EXISTS composite_all_diagnosis_breakdown_report;
