name: spt_cggnn
channels:
  - defaults
  - nvidia/label/cuda-11.8.0
  - dglteam/label/cu118
dependencies:
  - python==3.11
  - pip
  - conda-forge::libpq
  - bioconda::nextflow
  - cudatoolkit
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.8
  - dgl
  - pip:
    - spatialprofilingtoolbox[all]
  # Development dependencies
  - autopep8
  - pylint
