name: spt_cggnn
channels:
  - defaults
  - nvidia/label/cuda-11.8.0
  - dglteam/label/cu118  # remove /label/cu118 if you don't have a CUDA GPU
dependencies:
  - python==3.11
  - pip
  - conda-forge::libpq
  - bioconda::nextflow
  - cudatoolkit
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.8
  - dgl
  - pip:
    - spatialprofilingtoolbox[all]
# Remove lines with cuda in them if you don't have a CUDA GPU
# CUDA version is chosen by the latest version supported by DGL
