name: spt_cggnn
channels:
  - defaults
  - dglteam
dependencies:
  - python==3.11
  - pip
  - conda-forge::libpq
  - bioconda::nextflow
  - cudatoolkit
  - pytorch::pytorch
  - dgl
  - pip:
    - spatialprofilingtoolbox[all]
    - cg-gnn
  # Development dependencies
  - autopep8
  - pylint
  - isort
