#!/usr/bin/env python3
import argparse
import json
import socketserver
import os
import re

from log_formats import colorized_logger
logger = colorized_logger('spt-counts-server')


class CountsProvider:
    def __init__(self):
        self.load_expressions_indices()
        self.load_data_matrices()

    def load_expressions_indices(self):
        json_files = [f for f in os.listdir('.') if os.path.isfile(f) and re.search(r'\.json$', f)]
        if len(json_files) != 1:
            logger.error('Did not find index JSON file.')
            exit()
        with open(json_files[0], 'rt') as file:
            root = json.loads(file.read())
            entries = root[list(root.keys())[0]]
            self.studies = {}
            for entry in entries:
                self.studies[entry['specimen collection study name']] = entry

    def load_data_matrices(self):
        self.data_arrays = {}
        for study_name in self.get_study_names():
            self.data_arrays[study_name] = {
                specimen : self.get_data_array_from_file(filename)
                for specimen, filename in self.studies[study_name]['expressions files'].items()
            }

    def get_study_names(self):
        return self.studies.keys()

    def get_data_array_from_file(self, filename):
        data_array = []
        with open(filename, 'rb') as file:
            buffer = None
            while buffer != b'':
                buffer = file.read(8)
                data_array.append(int.from_bytes(buffer, 'little'))
        return data_array

    def compute_signature(self, channel_names, study_name):
        target_by_symbol = self.studies[study_name]['target by symbol']
        target_index_lookup = self.studies[study_name]['target index lookup']
        identifiers = [target_by_symbol[name] for name in channel_names]
        indices = [target_index_lookup[identifier] for identifier in identifiers]
        signature = 0
        for index in indices:
            signature = signature + (1 << index)
        return signature

    def count_structures_of_exact_signature(self, signature, study_name):
        counts = {}
        for specimen, data_array in self.data_arrays[study_name].items():
            count = 0
            for entry in self.get_data_array(study_name):
                if entry == signature:
                    count = count + 1
            counts[specimen] = count
        return counts

    def count_structures_of_partial_signature(self, signature, study_name):
        counts = {}
        for specimen, data_array in self.data_arrays[study_name].items():
            count = 0
            for entry in self.get_data_array(study_name):
                if entry | signature == entry:
                    count = count + 1
            counts[specimen] = count
        return counts


class CountsRequestHandler(socketserver.BaseRequestHandler):
    def handle(self):
        data = self.request.recv(512).strip()
        print(data)
        record_separator = chr(30)
        records = data.decode('utf-8').split(record_separator)
        study_name = records[0]
        channel_names = records[1:]
        print(study_name)
        print(channel_names)
        signature = self.server.counts_provider.compute_signature(channel_names, study_name)
        print(signature)
        print(f'{signature:064b}')
        count = self.server.counts_provider.count_structures_of_partial_signature(signature, study_name)
        self.request.sendall(count.to_bytes(8, 'little'))


if __name__=='__main__':
    parser = argparse.ArgumentParser(
        description = 'Server providing counts of samples satisfying given partial signatures.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        '--host',
        dest='host',
        type=str,
        default='localhost',
        help='The hostname or IP address on which to open the TCP socket.',
    )
    parser.add_argument(
        '--port',
        dest='port',
        type=str,
        default=8016,
        help='The port on which to open the TCP socket.',
    )
    args = parser.parse_args()

    counts_provider = CountsProvider()
    tcp_server = socketserver.TCPServer((args.host, args.port), CountsRequestHandler)
    tcp_server.counts_provider = counts_provider
    tcp_server.serve_forever()

